build_binary:
    builder: 'particle photon'
    source: 'app'
    
#     binary_name: my_binary
#     env_vars:
#         - $SPN_AWS_ACCESS_KEY_ID
#         - $SPN_AWS_SECRET_ACCESS_KEY
#         - $SPN_ESP32_THING_NAME
#         - $SPN_ESP32_WIFI_SSID
#         - $SPN_ESP32_WIFI_PASSWORD
#         - $SPN_ESP32_WIFI_SECURITY
        
# testing:
#     script: 'Scenario.py'
#     env_vars:
#         - $SPN_PARTICLE_TOKEN
#     device_update:
#          devices:
#             - $DEVICE_1    
#          ota_method: 'particle'
#          #binary: auto
#          binary: https://drive.google.com/open?id=1pqwckXPclrgKaeJy3-7hWkkfVH2b-61l
#          #binary: binary/mike_binary.bin
